# Generated by Django 3.1.5 on 2021-01-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='description',
            new_name='body',
        ),
    ]
